config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :categories
  resources :posts
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  mount Commontator::Engine => '/commontator'
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  validates :uri, presence: true, uniqueness: true
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates :uid, :provider, presence: true
  validates :uid, uniqueness: { scope: :provider }

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_commontable
  belongs_to :user
  belongs_to :category
  validates :title, :content, presence: true
  before_validation :cut_intro

  private

  def cut_intro
    if intro.blank? && !content.blank?
      self.intro = content.split.first(20).join(' ')
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_commontator

  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :trackable, :validatable, :confirmable, :omniauthable

  validates_format_of :email, without: TEMP_EMAIL_REGEX, on: :update
  has_many :identities, dependent: :destroy

  def admin?
    role == 'admin'
  end

  def self.find_for_oauth(auth, signed_in_resource = nil)
    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(email: email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          # username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0, 20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    email && email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :temporary_devise_resource

  protected
  def temporary_devise_resource
    @resource = User.new
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @category.destroy
    redirect_to posts_url, notice: 'Category was successfully destroyed.'
  end

  private
  def category_params
    params.require(:category).permit(:name, :uri)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)
    class_eval %{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)

        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:twitter, :facebook, :linked_in].each do |provider|
    provides_callback_for provider
  end

  def after_sign_in_path_for(resource)
    if resource.email_verified?
      super resource
    else
      finish_signup_path(resource)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]

  def index
    @posts = Post.page(params[:page]).per(10)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :intro, :content, :review, :state)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show # authorize! :read, @user
  end

  def edit # authorize! :update, @user
  end

  def update # authorize! :update, @user
    if @user.update(user_params)
      sign_in(@user == current_user ? @user : current_user, bypass: true)
      redirect_to @user, notice: 'Your profile was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def finish_signup # authorize! :update, @user
    if request.patch? && params[:user] # && params[:user][:email]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, bypass: true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  def destroy # authorize! :delete, @user
    @user.destroy
    redirect_to root_url
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    accessible = [:name, :email] # extend with your own params
    accessible << [:password, :password_confirmation] unless params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :uri %><br>
    <%= f.text_field :uri %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', posts_path %>

app/views/categories/index.html.erb
<p><%= link_to 'New category', new_category_path %></p>
<hr/>
<%- @categories.each do |f| %>
<%= link_to f.name, category_path(f.id)%>
<br/>
<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>uri:</strong>
  <%= @category.uri %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/inc/_footer.html.erb
<footer class="footer"> <!-- footer -->
  <div class="container">
    <div class="row">
      <div class="col-md-4"><!-- footer site details -->
        <div class="foot-left">
          <h5 class="foot-head-text">about us</h5><!-- footer-head-tag -->
          <img src="imgs/footer-logo.png" alt="//"/>
          <p>
            Nunc dictum est vel risus luctus eu venenatis dsapiending. Morbi mattis urna et felisNunc dictum est vel
            risus luctus eu venenatis sapien adipiscing. Morbi mattis urna et felisNunc dictum
          </p>
          <button class="btn foot-btns">read more</button>
        </div>
      </div>

      <div class="col-md-4"><!-- footer recent post -->
        <div class="clearfix"></div>
        <div class="foot-posts">
          <h5 class="foot-head-text">recent posts</h5><!-- footer-head-tag -->
          <div class="recent-posts"><!-- block 1 -->
            <div class="row">
              <div class="col-md-3 col-xs-2"><!-- post image -->
                <div class="recent-img-or">
                  <div class="recent-img">
                    <a href="single-blog.html">
                      <img src="http://placehold.it/70x70" alt="//"/>
                    </a>
                  </div>
                  <a href="single-blog.html">
                    <div class="figcaption">
                      <i class="fa fa-video-camera fa-lg"></i>
                    </div>
                  </a>
                </div>
              </div>
              <div class="col-md-9  col-xs-10"><!-- post details -->
                <div class="recent-post-text">
                  <a href="single-blog.html">
                    <span class="recent-text-head">Nullam id dolor id nibhDonec sed odio dui</span>
                  </a>
                  <a href="single-blog.html">
                    <span class="recent-text-comment">3comment</span>
                  </a>
                  <button class="btn foot-btns pull-right">read more</button>
                </div>
              </div>
            </div>
          </div>

          <div class="recent-posts"><!-- block 2 -->
            <div class="row">
              <div class="col-md-3 col-xs-2"><!-- post image -->
                <div class="recent-img-or">
                  <div class="recent-img">
                    <a href="single-blog.html">
                      <img src="http://placehold.it/70x70" alt="//"/>
                    </a>
                  </div>
                  <a href="single-blog.html">
                    <div class="figcaption">
                      <i class="fa fa-video-camera fa-lg"></i>
                    </div>
                  </a>
                </div>
              </div>
              <div class="col-md-9 col-xs-10"><!-- post details -->
                <div class="recent-post-text">
                  <a href="single-blog.html">
                    <span class="recent-text-head">Nullam id dolor id nibhDonec sed odio dui</span>
                  </a>
                  <a href="single-blog.html">
                    <span class="recent-text-comment">3comment</span>
                  </a>
                  <button class="btn foot-btns pull-right">read more</button>
                </div>
              </div>
            </div>
          </div>

          <div class="recent-posts"><!-- block 3 -->
            <div class="row">
              <div class="col-md-3 col-xs-2"><!-- post image -->
                <div class="recent-img-or">
                  <div class="recent-img">
                    <a href="single-blog.html">
                      <img src="http://placehold.it/70x70" alt="//"/>
                    </a>
                  </div>
                  <a href="single-blog.html">
                    <div class="figcaption">
                      <i class="fa fa-video-camera fa-lg"></i>
                    </div>
                  </a>
                </div>
              </div>
              <div class="col-md-9 col-xs-10"><!-- post details -->
                <div class="recent-post-text">
                  <a href="single-blog.html">
                    <span class="recent-text-head">Nullam id dolor id nibhDonec sed odio dui</span>
                  </a>
                  <a href="single-blog.html">
                    <span class="recent-text-comment">3comment</span>
                  </a>
                  <button class="btn foot-btns pull-right">read more</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4"><!-- flickr stream -->
        <div class="clearfix"></div>
        <div class="flickr">
          <h5 class="foot-head-text">flickr stream</h5><!-- footer-head-tag -->
          <ul id="basicuse" class="thumbs"></ul>
        </div>
      </div>
    </div>
  </div>
</footer>

<div class="foot-bar">
  <div class="container">
    <div class="row">
      <div class="foot-bar-m">
        <div class="col-sm-6">
          <div class="theme-rights">
				          <span>
						      Copyrights © 2012 & All Rights Reserved by Lion Codes.
						 </span>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="text-right">
				          <span class="foot-bar-link">
				              <a href="#">Privacy Policy</a>/
					          <a href="#">Terms of Service</a>/
					          <a href="#">FAQs</a>
					      </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/inc/_header.html.erb
<header class="top-bar">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <ul class="icons-bar">
          <li>
            <a class="icons-link" data-toggle="modal" data-target="#modal-1" href="#">
              <i class="fa fa-user fa-lg"></i>
            </a>
            <div class="modal-sign modal" id="modal-1" tabindex="-1" role="dialog">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <div class="sign-tabs">
                      <ul class="nav-sign">
                        <li class="active sign-in-bar">
                          <a href="#section-3" data-toggle="tab"><span>sign in</span></a>
                        </li>
                        <li class="sign-up-bar">
                          <a href="#section-4" data-toggle="tab"><span>sign up</span></a>
                        </li>
                      </ul>
                      <div class="tab-content">
                        <div class="sign-in-form tab-pane fade in active" id="section-3"> <!-- tab section-1 -->
                          <%= form_for(@resource, as: resource_name, url: session_path(resource_name), html: {role: 'form', class: 'sign-place'}) do |f| %>
                            <!-- sign -->
                            <span class="text-capitalize sign-title">
                              hello world, you can sign in by your e-mail here
                            </span>
                            <%= f.email_field :email, autofocus: true, class: "text-capitalize forms form-sign input-lg", placeholder: "user name" %>
                            <%= f.password_field :password, autocomplete: "off", class: "text-capitalize forms form-sign input-lg", placeholder: "password" %>
                            <input type="submit" value="sign in" class="btn btn-sign-forms" />
                          <% end %>
                          <a class="under-line-a" href="#">
                            <span class="text-capitalize alert-title">
                               forget password?
                            </span>
                          </a>
                        </div>
                        <div class="sign-up-form tab-pane fade" id="section-4"> <!-- tab section-2 -->
                          <form role="form" class="sign-place"><!-- sign -->
													      <span class="text-capitalize sign-title">
													          hello world, you can sign up by your e-mail here
													      </span>
                            <input type="text" class="text-capitalize forms form-sign input-lg" placeholder="user name">
                            <input type="text" class="text-capitalize forms form-sign input-lg" placeholder="e-mail">
                            <button type="button" class="btn btn-sign-forms">sign up</button>
                          </form>
                          <a class="under-line-a" href="#">
													      <span class="text-capitalize alert-title">
													          will send to you password via e-mail?
													      </span>
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <span class="top-lines">|</span>
          </li>
          <li>
            <a class="icons-link" data-toggle="modal" data-target="#modal-2" href="#">
              <i class="fa fa-search fa-lg"></i>
            </a>
            <div class="modal-search modal" id="modal-2" tabindex="-1" role="dialog">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <form role="form" class="sign-place"><!-- sign -->
                      <div class="search-modal-form">
                        <input type="text" class="text-capitalize forms form-sign input-lg" placeholder="search......">
                        <a href="#"><i class="fa fa-search fa-lg"></i></a>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <span class="top-lines">|</span>
          </li>
          <li>
            <a class="icons-link" href="#">
              <i class="fa fa-share-square fa-lg"></i>
            </a>
          </li>
          <li>
            <span class="top-lines">|</span>
          </li>
          <li>
            <a class="icons-link" href="#">
              <i class="fa fa-envelope fa-lg"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-sm-6">
        <div class="time-zone">
          <i class="fa fa-sun-o fa-lg"></i>
          <span class="text-top">FRIDAY 12/10/2013</span>
          <span class="text-top">|</span>
          <span class="text-top">12:00 AM</span>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/inc/_latest.html.erb
<div class="latest-cast"> <!-- latest cast-->
  <div class="container">
    <div class="row">
      <div class="col-md-12 hidden-xs">
        <div class="latest-cast-default">
          <div class="row">
            <div class="col-md-2 col-sm-2"><!-- cast drop down -->
              <div class="left-cast dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-chevron-circle-down fa-lg"></i>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">all news</a></li>
                  <!-- item -->
                  <li class="divider"></li>
                  <li><a href="#">movies news</a></li>
                  <!-- item -->
                  <li class="divider"></li>
                  <li><a href="#">music news</a></li>
                  <!-- item -->
                  <li class="divider"></li>
                  <li><a href="#">gmaes news</a></li>
                  <!-- item -->
                  <li class="divider"></li>
                  <li><a href="#">shop news</a></li>
                  <!-- item -->
                </ul>
                <div class="text-cast">
                  <span class="text-1">news</span>
                  <span class="text-2">movies</span>
                </div>
              </div>
            </div>

            <div class="col-md-10 col-sm-10"><!-- cast slider -->
              <div class="cast-slider carousel slide" data-ride="carousel" id="carousel-latest-cast">
                <div class="next-prev">
                  <div class="prev">
                    <a href="#carousel-latest-cast" data-slide="prev">
                      <i class="fa fa-angle-left fa-lg"></i>
                    </a>
                  </div>
                  <div class="next">
                    <a href="#carousel-latest-cast" data-slide="next">
                      <i class="fa fa-angle-right fa-lg"></i>
                    </a>
                  </div>
                </div>
                <ul class="slider-texts carousel-inner">
                  <li class="item active"><!-- item -->
                    <a href="#">
											  <span class="span-up">
											      We Provide Full suport and Full Help to our customers
											  </span>
                    </a>
										  <span class="span-under">
											  Sub title text line to describe your important message here
										  </span>
                  </li>
                  <li class="item"><!-- item -->
                    <a href="#">
											  <span class="span-up">
											      We Provide Full suport and Full Help to our customers demo
											  </span>
                    </a>
										  <span class="span-under">
											  Sub title text line to describe your important message here
										  </span>
                  </li>
                  <li class="item"><!-- item -->
                    <a href="#">
											  <span class="span-up">
											      We Provide Full suport and Full Help to our customers demo
											  </span>
                    </a>
										  <span class="span-under">
											  Sub title text line to describe your important message here
										  </span>
                  </li>
                </ul>
                <div class="cast-read-more">
                  <a href="#"><i class="fa fa-chevron-circle-right fa-lg"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/inc/_nav.html.erb
<nav class="navbar navbar-default" role="navigation"> <!-- Nav Bar -->
  <div class="container">
    <div class="row">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="" href="index.html"><%= image_tag "logo.png", class:"navbar-brand", alt: "//" %></a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="index.html" class="dropdown-toggle" data-toggle="dropdown">home<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <div class="caret-1"></div>
              </li>
              <li><a href="index.html">home</a></li>
              <li class="divider"></li>
              <li><a href="home2.html">home 2</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">pages<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <div class="caret-1"></div>
              </li>
              <li><a href="movies.html">movies</a></li>
              <li class="divider"></li>
              <li><a href="music.html">music</a></li>
              <li class="divider"></li>
              <li><a href="games.html">games</a></li>
              <li class="divider"></li>
              <li><a href="tech.html">tech</a></li>
              <li class="divider"></li>
              <li><a href="gallery.html">gallery</a></li>
            </ul>
          </li>
          <li><a href="shop.html">shop</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">PRODUCTS<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <div class="caret-1"></div>
              </li>
              <li><%= link_to 'all category', categories_path %></li>
              <li class="divider"></li>
              <li><a href="grid-view-product.html">GRID VIEW</a></li>
              <li class="divider"></li>
              <li><a href="list-view-product.html">LIST VIEW</a></li>
              <li class="divider"></li>
              <li><a href="single-product.html">SINGLE PRODUCTS</a></li>
              <li class="divider"></li>
              <li><a href="cart-check-out.html">CART CHECKOUT</a></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">BLOG<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <div class="caret-1"></div>
              </li>
              <li><a href="list-view-blog.html">LIST VIEW</a></li>
              <li class="divider"></li>
              <li><a href="grid-view-blog.html">GRID VIEW</a></li>
              <li class="divider"></li>
              <li><a href="single-blog.html">SINGLE BLOG</a></li>
              <li class="divider"></li>
              <li><a href="404.html">404 PAGE</a></li>
            </ul>
          </li>
          <li><a href="contact.html">CONTACT</a></li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>JazzOK</title>
  <meta name="description" content="JazzOK - magazine about lifestyle like a jazz"/>
  <meta name="keywords" content="jazz, music, live, video, movies, drink, whiskey"/>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='http://fonts.googleapis.com/css?family=Roboto:300,400,700,900' rel='stylesheet' type='text/css'/>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,700' rel='stylesheet' type='text/css'/>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>

<%= render 'inc/header' %>

<%= render 'inc/nav' %>

<%= render 'inc/mid_bar' %>

<%= render 'inc/latest' %>

<%= yield %>

<%= render 'inc/footer' %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :intro %><br>
    <%= f.text_area :intro %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">Please confirm your email address. No spam.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>